Repository boostcampwm-2022/web22-BooCrum, pull requests merged in 2022-12, with the labels that each got.

#171 [fix] move_object, scale_object 이벤트 구현 closes #168
  backend/src/socket/data-management.service.ts
  backend/src/socket/dto/object-map.vo.ts
  backend/src/socket/dto/object-move.dto.ts
  backend/src/socket/dto/object-scale.dto.ts
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️, BE

#173 [fix] delete 관련 버그 closes #127
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#174 [hotfix] init 이벤트 시 ObjectId 미반환 문제 해결 #168
  backend/src/object-database/object-handler.service.ts
  backend/src/socket/data-management.service.ts
Labels: 실시간 공유 편집, BE

#175 [chore] Grid line을 background로 설정 closes #172
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#177 [hotfix] move 모드에서 포스트잇 편집되는 부분 수정 closes #176
  frontend/package-lock.json
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#179 [feat] 작성자 표시 및 addObject 개선 closes #126
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/types/fabric-options.d.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#180 [feat] object group 이동구현
  frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/socket.utils.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, FE

#181 [Hotfix] Postit 관련 오류 수정
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#182 [fix] scale-object 이벤트 요청 응답 데이터 구조 변경 #161
  backend/src/socket/dto/object-scale.dto.ts
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, BE

#184 [hotfix] fe build error 수정
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
Labels: FE

#186 [fix] 로거 출력 시 콜스택과 메세지를 모두 출력하도록 변경 closes #185
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, BE

#206 [refactor] socket부분 코드 리팩토링
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object-to-server.ts
  frontend/src/utils/object.utils.ts
  frontend/src/utils/socket.utils.ts
  frontend/src/utils/type.utils.ts
Labels: 실시간 공유 편집, FE

#199 [feat] Thumbnail 업로드 및 조회 API 구현 closes #198
  backend/package-lock.json
  backend/package.json
  backend/src/workspace/file-interceptor/thumbnail.interceptor.ts
  backend/src/workspace/workspace.controller.ts
  backend/src/workspace/workspace.service.ts
Labels: BE

#211 [feat] Socket 서버 move_object 이벤트 rollback closes #210
  backend/src/socket/dto/object-move.dto.ts
  backend/src/socket/socket.gateway.ts
Labels: 워크스페이스 관리, 중요도⭐️⭐️, BE

#213 [hotfix] thumbnail 업데이트 관련 예외처리 추가 #198
  backend/src/workspace/workspace.service.ts
Labels: 워크스페이스 관리, 중요도⭐️⭐️, BE

#209 [feat] Pen 메뉴 컴포넌트 구현 closes #200 #201
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/workspace/pen-type-box/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#214 [feat] 오브젝트 색상 수정 closes #195
  frontend/src/components/context-menu/index.style.tsx
  frontend/src/pages/main/workspace-menu/index.style.tsx
  frontend/src/pages/workspace/object-edit-menu/index.style.tsx
  frontend/src/pages/workspace/object-edit-menu/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object-to-server.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#212 [feat] MongoDB 전환 시도 closes #192
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/object-database/abstract/object-database.interface.ts
  backend/src/object-database/abstract/object-handler.abstract.ts
  backend/src/object-database/abstract/workspace-object.interface.ts
  backend/src/object-database/dto/create-object.dto.ts
  backend/src/object-database/dto/update-object.dto.ts
  backend/src/object-database/entity/workspace-object.entity.ts
  backend/src/object-database/mongoose-object-handler.service.spec.ts
  backend/src/object-database/mongoose-object-handler.service.ts
  backend/src/object-database/object-database.module.ts
  backend/src/object-database/object-handler.service.ts
  backend/src/object-database/schema/object-bucket.schema.ts
  backend/src/object-database/schema/workspace-object.schema.ts
  backend/src/socket/dto/object-map.vo.ts
  backend/src/socket/dto/object.dto.ts
  backend/src/socket/guard/user-role.guard.ts
  backend/src/socket/object-management.service.ts
  backend/src/socket/pipe/object-transform.pipe.ts
  backend/src/socket/socket.gateway.ts
  backend/src/types/object.d.ts
Labels: 화이트보드, 실시간 공유 편집, BE

#215 [feat] 포스트잇 폰트 크기 수정 closes #196
  frontend/src/pages/workspace/header/index.style.tsx
  frontend/src/pages/workspace/object-edit-menu/index.tsx
  frontend/src/pages/workspace/object-edit-menu/index.type.ts
  frontend/src/pages/workspace/toolkit/index.style.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-to-server.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#217 [feat] Role 권한 수정 Event Handler 추가 closes #216
  backend/src/socket/db-access.service.ts
  backend/src/socket/dto/change-role.dto.ts
  backend/src/socket/socket.gateway.ts
Labels: 워크스페이스 관리, 화이트보드, BE

#222 [feat] 템플릿 목록 조회 및 캔버스 복제 기능 추가
  backend/src/object-database/schema/template-bucket.schema.ts
  backend/src/workspace/workspace.controller.ts
  backend/src/workspace/workspace.module.ts
  backend/src/workspace/workspace.service.ts
Labels: 워크스페이스 관리, BE

#225 [hotfix] Update 유효성 검증 로직 오류 수정 fix #192
  backend/src/socket/pipe/object-transform.pipe.ts
Labels: 실시간 공유 편집, BE

#229 [chore] background 깜빡임 현상 수정 closes #228
  frontend/src/pages/workspace/whiteboard-canvas/index.style.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#240 [fix] postit에 usernickname 표시 #126
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/object-from-server.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#238 [feat] Path string 압축 closes #235
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object-to-server.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#242 [feat] 워크스페이스 부분 조회 기능 추가 #239
  backend/src/socket/db-access.service.ts
  backend/src/types/workspace.d.ts
  backend/src/user/dto/partial-search.dto.ts
  backend/src/user/pipe/part-search-transform.pipe.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: 워크스페이스 관리, BE

#241 [feat] 화이트보드 UX 개선
  frontend/src/pages/workspace/whiteboard-canvas/index.style.tsx
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️, FE

#257 [feat] 리뷰 개선사항 반영 closes #249
  frontend/src/assets/icon/alarm.svg
  frontend/src/components/user-profile/index.style.tsx
  frontend/src/pages/main/header/index.tsx
  frontend/src/pages/workspace/current-user-list/index.style.tsx
  frontend/src/pages/workspace/current-user-list/index.tsx
  frontend/src/pages/workspace/pen-type-box/index.style.tsx
  frontend/src/pages/workspace/pen-type-box/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
  frontend/src/utils/object-to-server.ts
  frontend/src/utils/object.utils.ts
Labels: 중요도⭐️⭐️⭐️, FE

#263 [feat] updating_object 이벤트 구현 closes #262
  backend/src/socket/pipe/object-updating.pipe.ts
  backend/src/socket/socket.gateway.ts
Labels: 중요도⭐️, BE

#261 [feat] Event 분석을 위한 Log 추가 closes #258
  backend/src/socket/socket.gateway.ts
Labels: 중요도⭐️, BE

#268 [feat] Socket 서버의 Data를 Redis로 관리 closes #243
  backend/package-lock.json
  backend/package.json
  backend/src/socket/guard/user-role.guard.ts
  backend/src/socket/socket.gateway.ts
  backend/src/socket/socket.module.ts
  backend/src/socket/user-management.service.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️, BE

#270 [refactor] 서버 확장을 위한 Socket.IO 서버 코드 리팩토링 closes #237
  backend/package-lock.json
  backend/package.json
  backend/pm2-config.json
  backend/src/main.ts
  backend/src/socket/adapter/custom-socket.adapter.ts
  backend/src/socket/socket.gateway.ts
Labels: 중요도⭐️⭐️⭐️, BE

#272 [feat] UX 개선 및 무한 스크롤 추가
  frontend/src/api/user.ts
  frontend/src/data/workspace-order.ts
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/workspace/member-role/index.tsx
  frontend/src/pages/workspace/zoom-controller/index.style.tsx
  frontend/src/utils/convert-time.utils.ts
Labels: 중요도⭐️, FE

#275 [fix] 웹소켓 서버 long polling 비활성화 closes #274
  backend/package-lock.json
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, BE

#276 Revert "[fix] 웹소켓 서버 long polling 비활성화 closes #274"
  backend/package-lock.json
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, BE

#278 [fix] 백엔드 Object 캐시 제거
  backend/src/socket/object-management.service.ts
Labels: 실시간 공유 편집, BE

#279 [hotfix]: be - 객체 Object 제거 오류 수정
  backend/src/socket/object-management.service.ts
Labels: 실시간 공유 편집, BE

#281 [hotfix] draw object rendering error
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object-to-server.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#288 [hotfix] init 시 creator 수정 시에 지정한 Type과 실제 Type의 불일치로 인한 오류 수정 #286
  backend/src/object-database/mongoose-object-handler.service.ts
  backend/src/socket/db-access.service.ts
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, BE

#290 [hotfix] create 로직 오류 수정 #286
  backend/src/object-database/mongoose-object-handler.service.ts
Labels: 실시간 공유 편집, BE

#285 [feat] 텍스트 공동 편집 closes #273
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️, FE

#284 [feat] 캔버스 렌더링 최적화 closes #271
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
  frontend/src/pages/workspace/whiteboard-canvas/useObjectWorker.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#293 [fix] 소켓 서버 Polling 비활성화
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, BE

#294 [fix] draw object index leveling closes #271
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#291 [chore] Lighthouse 성능 측정 및 개선 closes #289
  frontend/src/App.tsx
  frontend/src/components/logo/index.tsx
  frontend/src/components/user-profile/index.style.tsx
  frontend/src/pages/main/workspace-card/index.style.tsx
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/workspace/header/index.tsx
  frontend/src/pages/workspace/right-side/index.style.tsx
  frontend/src/pages/workspace/toolkit/index.tsx
  frontend/src/pages/workspace/zoom-controller/index.style.tsx
  frontend/src/pages/workspace/zoom-controller/index.tsx
  frontend/src/utils/convert-time.utils.ts
Labels: 중요도⭐️, FE

#300 [feat] select 관련 UI 개선 #271
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️, FE

#301 [fix] object caching 기능 끔 #271
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️, FE

#298 [feat] 테스트 코드 검증을 위한 사전 작업 closes #283
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.spec.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/object-database/mongoose-object-handler.service.spec.ts
  backend/src/object-database/object-database.controller.spec.ts
  backend/src/object-database/object-handler.service.spec.ts
  backend/src/socket/object-management.service.spec.ts
  backend/src/socket/socket.gateway.spec.ts
  backend/src/socket/user-management.service.spec.ts
  backend/src/team/team.controller.spec.ts
  backend/src/team/team.controller.ts
  backend/src/team/team.module.ts
  backend/src/team/team.service.spec.ts
  backend/src/team/team.service.ts
  backend/src/user/user.controller.spec.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.spec.ts
  backend/src/user/user.service.ts
  backend/src/workspace/workspace.controller.spec.ts
  backend/src/workspace/workspace.service.spec.ts
Labels: BE

#302 [feat] 트랙패드 뒤로가기 방지 closes #234
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️, FE
