Repository boostcampwm-2022/web22-BooCrum, pull requests merged in 2022-11, with the labels that each got.

#17 [feat] 메인페이지 화면 레이아웃 구현 closes #10
  .DS_Store
  frontend/src/App.tsx
  frontend/src/assets/icon/alarm.svg
  frontend/src/components/logo/index.style.tsx
  frontend/src/components/logo/index.tsx
  frontend/src/global.style.tsx
  frontend/src/index.tsx
  frontend/src/pages/main/header.component.tsx
  frontend/src/pages/main/header.style.tsx
  frontend/src/pages/main/index.style.tsx
  frontend/src/pages/main/index.tsx
  frontend/src/pages/main/sidebar.component.tsx
  frontend/src/pages/main/sidebar.style.tsx
  util/.DS_Store
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#29 [feat] Workspace 목록 Component 구현 closes #23
  frontend/.eslintrc
  frontend/src/pages/main/worksapce-card.style.tsx
  frontend/src/pages/main/workspace-card.component.tsx
  frontend/src/pages/main/workspace-list.component.tsx
  frontend/src/pages/main/workspace-list.style.tsx
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#35 [feat] 워크스페이스 recent, all workspaces 화면 구현 closes #13
  frontend/src/assets/icon/boo-crum.png
  frontend/src/context/main-workspace.ts
  frontend/src/data/workspace-sidebar.tsx
  frontend/src/global.style.tsx
  frontend/src/pages/error/index.style.tsx
  frontend/src/pages/error/index.tsx
  frontend/src/pages/main/all-workspace/index.style.tsx
  frontend/src/pages/main/all-workspace/index.tsx
  frontend/src/pages/main/contents/index.style.tsx
  frontend/src/pages/main/contents/index.tsx
  frontend/src/pages/main/header/index.style.tsx
  frontend/src/pages/main/header/index.tsx
  frontend/src/pages/main/index.tsx
  frontend/src/pages/main/recent-workspace/index.style.tsx
  frontend/src/pages/main/recent-workspace/index.tsx
  frontend/src/pages/main/sidebar.component.tsx
  frontend/src/pages/main/sidebar/index.style.tsx
  frontend/src/pages/main/sidebar/index.tsx
  frontend/src/pages/main/workspace-card.component.tsx
  frontend/src/pages/main/workspace-card/index.style.tsx
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/main/workspace-list/index.style.tsx
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/main/workspace-template-list/index.style.tsx
  frontend/src/pages/main/workspace-template-list/index.tsx
  frontend/src/pages/main/workspace-template/index.style.tsx
  frontend/src/pages/main/workspace-template/index.tsx
  frontend/src/types/main-workspace.d.ts
  frontend/tsconfig.json
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#36 [feat] 워크스페이스 정렬 dropdown 컴포넌트 구현 closes #14
  frontend/src/App.tsx
  frontend/src/assets/icon/dropdown-active.svg
  frontend/src/assets/icon/dropdown-inactive.svg
  frontend/src/components/logo/index.tsx
  frontend/src/context/main-workspace.ts
  frontend/src/data/workspace-order.ts
  frontend/src/data/workspace-sidebar.tsx
  frontend/src/data/workspace-templates.ts
  frontend/src/global.style.tsx
  frontend/src/hooks/useDropdown.tsx
  frontend/src/pages/error/index.tsx
  frontend/src/pages/login/index.tsx
  frontend/src/pages/main/all-workspace/index.style.tsx
  frontend/src/pages/main/all-workspace/index.tsx
  frontend/src/pages/main/order-dropdown/index.style.tsx
  frontend/src/pages/main/order-dropdown/index.tsx
  frontend/src/pages/main/recent-workspace/index.style.tsx
  frontend/src/pages/main/recent-workspace/index.tsx
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/main/workspace-list/index.style.tsx
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/types/main-workspace.d.ts
Labels: 워크스페이스 관리, 중요도⭐️, FE

#37 [feat] 로그인/로그아웃 및 유저 CRUD closes #5, #7
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/guard/github.guard.ts
  backend/src/auth/guard/session.guard.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/main.ts
  backend/src/middlewares/session.middleware.ts
  backend/src/team/entity/team-member.entity.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/entity/user.entity.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/src/workspace/entity/workspace-member.entity.ts
  backend/src/workspace/entity/workspace.entity.ts
Labels: BE

#39 [feat] 로그인 페이지 화면 구현 closes #30
  frontend/src/App.tsx
  frontend/src/assets/icon/github-login.svg
  frontend/src/assets/image/hero-image.png
  frontend/src/components/github-login-button/index.style.tsx
  frontend/src/components/github-login-button/index.tsx
  frontend/src/pages/login/hero-content/index.style.tsx
  frontend/src/pages/login/hero-content/index.tsx
  frontend/src/pages/login/hero-image/index.style.tsx
  frontend/src/pages/login/hero-image/index.tsx
  frontend/src/pages/login/index.style.tsx
  frontend/src/pages/login/index.tsx
  frontend/src/pages/login/login-content/index.style.tsx
  frontend/src/pages/login/login-content/index.tsx
Labels: 인증, 중요도⭐️⭐️, FE

#38 [feat] New Workspace 라우팅 기능 구현 closes #12
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/hooks/useDropdown.ts
  frontend/src/index.tsx
  frontend/src/pages/main/workspace-template/index.tsx
  frontend/src/pages/workspace/index.style.tsx
  frontend/src/pages/workspace/index.tsx
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#40 [feat] 이름 변경 Modal 구현 외 2개 closes #24 #25 #26
  frontend/src/components/context-menu/index.style.tsx
  frontend/src/components/context-menu/index.tsx
  frontend/src/components/context-menu/index.types.ts
  frontend/src/components/modal/index.style.tsx
  frontend/src/components/modal/index.ts
  frontend/src/components/modal/index.tsx
  frontend/src/components/modal/index.types.ts
  frontend/src/context/index.ts
  frontend/src/data/index.ts
  frontend/src/global.style.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useContextMenu.tsx
  frontend/src/hooks/useModal.tsx
  frontend/src/pages/main/delete-modal/index.style.tsx
  frontend/src/pages/main/delete-modal/index.tsx
  frontend/src/pages/main/delete-modal/index.types.ts
  frontend/src/pages/main/rename-modal/index.style.tsx
  frontend/src/pages/main/rename-modal/index.tsx
  frontend/src/pages/main/rename-modal/index.types.ts
  frontend/src/pages/main/workspace-card/index.style.tsx
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/main/workspace-menu/index.style.tsx
  frontend/src/pages/main/workspace-menu/index.tsx
  frontend/src/pages/main/workspace-menu/index.types.ts
  frontend/src/types/index.d.ts
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#42 [feat] 권한에 따른 라우팅 구현, 로그인 로직 구현 closes #32 #31
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/gif/spinner.gif
  frontend/src/components/github-login-button/index.style.tsx
  frontend/src/components/github-login-button/index.tsx
  frontend/src/components/loading/index.style.tsx
  frontend/src/components/loading/index.tsx
  frontend/src/components/protected-route/index.tsx
  frontend/src/context/auth.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/pages/login/index.tsx
Labels: 인증, 중요도⭐️⭐️⭐️, FE

#45 [feat] 사용자 프로필 컴포넌트 구현 closes #34
  frontend/src/assets/icon/logout.svg
  frontend/src/assets/icon/user-profile.svg
  frontend/src/components/user-profile/index.style.tsx
  frontend/src/components/user-profile/index.tsx
  frontend/src/hooks/useContextMenu.tsx
  frontend/src/pages/main/header/index.tsx
Labels: 인증, 중요도⭐️⭐️⭐️, FE

#47 [feat] All Workspace API 연동 closes #15
  frontend/src/data/workspace-order.ts
  frontend/src/pages/main/order-dropdown/index.style.tsx
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/main/workspace-card/index.type.ts
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/main/workspace-list/index.type.ts
  frontend/src/types/main-workspace.d.ts
  frontend/src/utils/index.ts
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#49 [fix] API 명세 작성 및 검토, Github Action 추가 closes #5, #48, #50
  .github/workflows/deploy.yml
  backend/README.md
  backend/src/auth/auth.controller.ts
  backend/src/auth/filter/unauth-redirect.filter.ts
  backend/src/auth/strategy/github.strategy.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  backend/src/workspace/workspace.controller.ts
  backend/src/workspace/workspace.service.ts
Labels: 중요도⭐️⭐️⭐️, BE

#52 [feat] 로그인, 로그아웃, 인증 api 연동 FE closes #51
  frontend/src/components/user-profile/index.tsx
  frontend/src/hooks/useAuth.ts
Labels: 인증, 중요도⭐️⭐️⭐️, FE

#54 [fix] login api 동작 방식 변경 closes #51
  backend/package-lock.json
  backend/package.json
  backend/src/auth/guard/session.guard.ts
Labels: 인증, BE

#55 [refactor] API 패칭 분리 closes #15
  frontend/src/api/user.ts
  frontend/src/components/user-profile/index.tsx
  frontend/src/hooks/useDropdown.ts
  frontend/src/hooks/useModal.tsx
  frontend/src/pages/main/order-dropdown/index.tsx
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/tsconfig.json
Labels: 워크스페이스 관리, FE

#57 [feat] API 패칭 분리 close #56
  frontend/package.json
  frontend/src/api/user.ts
  frontend/src/api/user.types.ts
  frontend/src/components/user-profile/index.tsx
  frontend/src/pages/main/workspace-list/index.tsx
Labels: FE

#59 [feat] workspace 생성 api 패칭 closes #58
  frontend/src/api/user.ts
  frontend/src/api/workspace.ts
  frontend/src/api/workspace.type.ts
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/main/workspace-template/index.tsx
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, FE

#67 [fix] workspace API 요구사항 반영 closes #60
  backend/src/user/user.service.ts
  backend/src/workspace/dto/workspaceCreateRequest.dto.ts
  backend/src/workspace/entity/workspace.entity.ts
  backend/src/workspace/workspace.service.ts
Labels: BE

#70 [feat] Socket 서버 구축 #66
  backend/package-lock.json
  backend/package.json
  backend/src/app.gateway.ts
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/workspace/entity/workspace-member.entity.ts
  backend/src/workspace/workspace.controller.ts
  backend/src/workspace/workspace.service.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, BE

#71 [feat] ObjectDatabase 생성/삭제/조회 기능 구현 #65
  backend/src/app.module.ts
  backend/src/object-database/constant/object-database.constant.ts
  backend/src/object-database/dto/create-table-request.dto.ts
  backend/src/object-database/object-database.controller.spec.ts
  backend/src/object-database/object-database.controller.ts
  backend/src/object-database/object-database.module.ts
  backend/src/object-database/object-database.service.spec.ts
  backend/src/object-database/object-database.service.ts
Labels: 워크스페이스 관리, 중요도⭐️⭐️⭐️, BE

#72 [feat] Workspace 내부 Object CRUD API 구현 closes #9
  backend/src/object-database/dto/create-object.dto.ts
  backend/src/object-database/dto/select-object.dto.ts
  backend/src/object-database/object-database.controller.ts
  backend/src/object-database/object-database.module.ts
  backend/src/object-database/object-handler.service.spec.ts
  backend/src/object-database/object-handler.service.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, BE

#73 [fix] TypeORM Migration 수정 fix #60
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/migrations/1669037051304-add-thumbnail-on-workspace.ts
  backend/src/object-database/object-database.module.ts
  backend/src/ormconfig.ts
  backend/src/team/entity/team-member.entity.ts
  backend/src/team/entity/team.entity.ts
  backend/src/team/team.controller.ts
  backend/src/team/team.service.ts
  backend/src/user/entity/user.entity.ts
  backend/src/user/user.service.ts
  backend/src/workspace/workspace.service.ts
Labels: 워크스페이스 관리, BE

#78 [feat] Workspace 기능과 ObjectDataBase 기능 연결
  backend/src/object-database/constant/object-database.constant.ts
  backend/src/object-database/object-database.controller.ts
  backend/src/object-database/object-database.module.ts
  backend/src/object-database/object-database.service.ts
  backend/src/object-database/object-handler.service.ts
  backend/src/workspace/workspace.module.ts
  backend/src/workspace/workspace.service.ts
Labels: 워크스페이스 관리, BE

#79 [feat] Toolkit 컴포넌트 구현 closes #61
  frontend/src/assets/icon/dropdown-active.svg
  frontend/src/assets/icon/dropdown-inactive.svg
  frontend/src/assets/icon/toolkit-move-cursor.svg
  frontend/src/assets/icon/toolkit-select-cursor.svg
  frontend/src/assets/image/eraser.png
  frontend/src/assets/image/pen.png
  frontend/src/assets/image/post-it.svg
  frontend/src/assets/image/section.svg
  frontend/src/context/workspace.ts
  frontend/src/data/workspace-object-color.ts
  frontend/src/data/workspace-tool.ts
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/workspace/index.tsx
  frontend/src/pages/workspace/penTypeBox/index.style.tsx
  frontend/src/pages/workspace/penTypeBox/index.tsx
  frontend/src/pages/workspace/toolkit/index.style.tsx
  frontend/src/pages/workspace/toolkit/index.tsx
  frontend/src/utils/convert-time.utils.ts
  frontend/src/utils/is-selected-cursor.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#80 [feat] 화이트보드 Canvas 기본 설정 closes #75
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/workspace/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.style.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#81 [feat] 화이트보드 헤더 구현 closes #62
  frontend/src/assets/icon/export.png
  frontend/src/assets/icon/share.svg
  frontend/src/assets/icon/zoom-in.svg
  frontend/src/assets/icon/zoom-out.svg
  frontend/src/context/workspace.ts
  frontend/src/pages/workspace/header/index.style.tsx
  frontend/src/pages/workspace/header/index.tsx
  frontend/src/pages/workspace/index.tsx
  frontend/src/pages/workspace/layout/index.tsx
  frontend/src/pages/workspace/left-side/index.style.tsx
  frontend/src/pages/workspace/left-side/index.tsx
  frontend/src/pages/workspace/pen-type-box/index.style.tsx
  frontend/src/pages/workspace/pen-type-box/index.tsx
  frontend/src/pages/workspace/right-side/index.style.tsx
  frontend/src/pages/workspace/right-side/index.tsx
  frontend/src/pages/workspace/toolkit/index.style.tsx
  frontend/src/pages/workspace/toolkit/index.tsx
  frontend/src/pages/workspace/user-list/index.style.tsx
  frontend/src/pages/workspace/user-list/index.tsx
  frontend/src/pages/workspace/zoom-controller/index.style.tsx
  frontend/src/pages/workspace/zoom-controller/index.tsx
  frontend/src/utils/convert-time.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#92 [feat] Socket 서버와 Express-Session 연결 #66
  backend/src/app.gateway.ts
  backend/src/main.ts
  backend/src/util/session.util.ts
Labels: 실시간 공유 편집, BE

#89 [feat] 소켓 연결 설정 closes #82
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.types.tsx
  frontend/src/pages/workspace/whiteboard-canvas/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, FE

#90 [feat] 객체 추가 & 삭제 로직 구현closes #84
  frontend/package-lock.json
  frontend/package.json
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.types.ts
  frontend/src/utils/fabric.utils.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, FE

#93 [feat] 소켓 이벤트 일부 구현 #66
  backend/package-lock.json
  backend/src/app.gateway.ts
  backend/src/user-map.vo.ts
Labels: 실시간 공유 편집, BE

#94 [refactor] 소켓 변수 ref로 변경
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
Labels: 실시간 공유 편집, FE

#96 [fix] Socket API 요청 주소 변경 #66
  backend/src/app.gateway.ts
  backend/src/object.dto.ts
  backend/src/user-map.vo.ts
Labels: 실시간 공유 편집, BE

#97 [fix] Socket Disconnect 로직 수정 #66
  backend/src/app.gateway.ts
Labels: 실시간 공유 편집, BE

#99 [feat] Socket 이벤트 구현 closes #66
  backend/src/app.gateway.ts
  backend/src/object.dto.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, BE

#101 [fix] API 요청 시 workspaceId 고정 ID 제거 #66
  backend/src/app.gateway.ts
Labels: 실시간 공유 편집, BE

#95 [feat] Object edit menu 컴포넌트 및 커서 수정 구현 closes #63 #64
  frontend/src/assets/icon/cursor.cur
  frontend/src/assets/icon/dropdown-color.svg
  frontend/src/assets/icon/rename-section.svg
  frontend/src/components/context-menu/index.style.tsx
  frontend/src/data/workspace-object-color.ts
  frontend/src/global.style.tsx
  frontend/src/pages/main/index.style.tsx
  frontend/src/pages/main/sidebar/index.style.tsx
  frontend/src/pages/main/workspace-menu/index.style.tsx
  frontend/src/pages/workspace/object-edit-menu/index.style.tsx
  frontend/src/pages/workspace/object-edit-menu/index.tsx
  frontend/src/pages/workspace/object-edit-menu/index.type.ts
  frontend/src/pages/workspace/user-list/index.style.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#103 [refactor] Socket 관련 디렉토리 및 코드 정리 #66
  backend/src/app.gateway.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/src/middlewares/session.middleware.ts
  backend/src/util/session.util.ts
  backend/src/util/socket/object.dto.ts
  backend/src/util/socket/user-map.vo.ts
  backend/src/util/socket/user.dao.ts
Labels: 실시간 공유 편집, BE

#98 [feat] 화이트보드 화면 이동 closes #76
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#104 [fix] 소켓 연결해제 구현
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
Labels: 실시간 공유 편집, FE

#108 [refactor] Guest userId, nickname 변경 및 enter_user 이벤트 시 color 값 전달 #66
  backend/src/app.gateway.ts
  backend/src/util/socket/user.dao.ts
Labels: 실시간 공유 편집, BE

#106 [feat] 화이트보드 Canvas 휠 기반 화면이동 구현 closes #76
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/utils/fabric.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#109 [feat] object 생성 구현 closes #105
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/hooks/useContextMenu.tsx
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#110 [feat] 마우스 포인터 실시간 공유 구현
  frontend/src/context/workspace.ts
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/types/workspace-member.d.ts
  frontend/src/types/workspace.d.ts
  frontend/src/utils/fabric.utils.ts
Labels: FE

#112 [refactor] workspace type 폴더 구조 변경 및 re-exporting
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/context/workspace.ts
  frontend/src/pages/workspace/whiteboard-canvas/index.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/index.types.tsx
  frontend/src/pages/workspace/whiteboard-canvas/types/index.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-member.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/types/workspace.d.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/socket.utils.ts
Labels: 중요도⭐️⭐️⭐️, FE

#113 [refactor] - userProfile을 전역 상태로 관리
  frontend/src/components/user-profile/index.tsx
  frontend/src/context/auth.ts
  frontend/src/context/user.ts
  frontend/src/hooks/useAuth.ts
Labels: FE

#114 [feat] 유저 권한 조회 시 Workspace 확인 및 로그인 유저 최초 접근 시 DB에 기록 #72
  backend/src/auth/auth.controller.ts
  backend/src/auth/filter/unauth-redirect.filter.ts
  backend/src/socket/db-access.service.ts
  backend/src/socket/socket.gateway.ts
  backend/src/team/team.service.ts
Labels: 워크스페이스 관리, 실시간 공유 편집, BE

#115 [feat] Object interacting 추가 closes #77
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/socket.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#119 [feat] workspace url 설정 closes #116
  frontend/src/App.tsx
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/main/workspace-template/index.tsx
Labels: 워크스페이스 초대 기능, 중요도⭐️⭐️⭐️, FE

#120 [feat] Object Delete Action 추가 closes #77
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#124 [feat] EditMenu 위치 설정 closes #123
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#125 [feat] workspace share 모달 구현 closes #117
  frontend/.gitignore
  frontend/src/api/workspace.ts
  frontend/src/api/workspace.type.ts
  frontend/src/assets/icon/close.svg
  frontend/src/assets/icon/copy-link.svg
  frontend/src/components/toast-message/index.style.tsx
  frontend/src/components/toast-message/index.tsx
  frontend/src/pages/workspace/header/index.tsx
  frontend/src/pages/workspace/index.tsx
  frontend/src/pages/workspace/layout/index.tsx
  frontend/src/pages/workspace/right-side/index.tsx
  frontend/src/pages/workspace/share-modal/index.style.tsx
  frontend/src/pages/workspace/share-modal/index.tsx
  frontend/src/pages/workspace/share-modal/index.type.ts
Labels: 워크스페이스 초대 기능, 중요도⭐️⭐️⭐️, FE

#133 [fix] Object Entity 구조 변경 closes #132
  backend/src/migrations/1669621214094-change-object-columns.ts
  backend/src/object-database/dto/create-object.dto.ts
  backend/src/object-database/dto/update-object.dto.ts
  backend/src/object-database/entity/workspace-object.entity.ts
  backend/src/socket/db-access.service.ts
  backend/src/socket/socket.gateway.ts
  backend/src/util/socket/object.dto.ts
Labels: 워크스페이스 관리, BE

#135 [hotfix] 화이트보드 객체 업데이트 및 삭제 로직 오류 긴급 수정 #132
  backend/src/migrations/1669621214094-change-object-columns.ts
  backend/src/object-database/object-handler.service.ts
  backend/src/socket/socket.gateway.ts
  backend/src/user/user.service.ts
  backend/src/util/socket/user.dao.ts
Labels: 워크스페이스 관리, BE

#137 [fix] User Role 타입 정의 및 Member 테이블 Role 컬럼 타입 수정 closes #121
  backend/src/migrations/1669639570300-change-role-type.ts
  backend/src/socket/db-access.service.ts
  backend/src/socket/dto/object.dto.ts
  backend/src/socket/dto/user-map.vo.ts
  backend/src/socket/dto/user.dao.ts
  backend/src/socket/socket.gateway.ts
  backend/src/team/entity/team-member.entity.ts
  backend/src/team/enum/role.enum.ts
  backend/src/team/team.controller.ts
  backend/src/team/team.service.ts
  backend/src/user/user.service.ts
  backend/src/util/constant/role.constant.ts
  backend/src/workspace/entity/workspace-member.entity.ts
  backend/src/workspace/workspace.controller.ts
  backend/src/workspace/workspace.service.ts
Labels: 워크스페이스 관리, 중요도⭐️⭐️, BE

#136 [feat] - object 타입 재정의 및 포멧팅 함수 구현
  frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace.types.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/socket.utils.ts
Labels: 실시간 공유 편집, FE

#139 [fix] Section 제목 최대 길이 설정 closes #138
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, 중요도⭐️, BE

#141 [feat] 작업내용 closes #140
  backend/src/migrations/1669639570300-change-role-type.ts
  backend/src/team/entity/team-member.entity.ts
  backend/src/workspace/entity/workspace-member.entity.ts
Labels: 실시간 공유 편집, 중요도⭐️, BE

#144 [hotfix] Role 탐색 및 추가 로직 리턴 타입 수정
  backend/src/socket/db-access.service.ts
Labels: 워크스페이스 관리, 실시간 공유 편집, BE

#143 [feat] 접속중인 사용자 목록 구현 closes #118
  frontend/public/index.html
  frontend/public/logo.png
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/src/assets/icon/user-icon.svg
  frontend/src/components/modal/index.style.tsx
  frontend/src/data/workspace-order.ts
  frontend/src/pages/main/workspace-card/index.tsx
  frontend/src/pages/main/workspace-list/index.tsx
  frontend/src/pages/workspace/share-modal/index.tsx
  frontend/src/pages/workspace/toolkit/index.style.tsx
  frontend/src/pages/workspace/user-list/index.style.tsx
  frontend/src/pages/workspace/user-list/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
Labels: 실시간 공유 편집, 중요도⭐️⭐️, FE

#147 [refactor] 워크스페이스 컴포넌트 레이아웃 리팩토링 closes #146
  frontend/public/manifest.json
  frontend/src/components/logo/index.tsx
  frontend/src/pages/workspace/header/index.tsx
  frontend/src/pages/workspace/header/index.type.ts
  frontend/src/pages/workspace/index.tsx
  frontend/src/pages/workspace/layout/index.style.tsx
  frontend/src/pages/workspace/layout/index.tsx
  frontend/src/pages/workspace/toolkit/index.tsx
Labels: 중요도⭐️, FE

#148 [hotfix] UserDAO 생성자의 role이 누락된 부분 수정 #121
  backend/src/socket/dto/user.dao.ts
Labels: 워크스페이스 관리, 실시간 공유 편집, BE

#142 [feat] addPostIt 구현 closes #126
  frontend/src/pages/workspace/whiteboard-canvas/useEditMenu.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#145 [refactor] 소켓 서버 데이터 관리 객체 구현 closes #122
  backend/src/socket/data-management.service.spec.ts
  backend/src/socket/data-management.service.ts
  backend/src/socket/db-access.service.ts
  backend/src/socket/dto/user-map.vo.ts
  backend/src/socket/socket.gateway.ts
  backend/src/socket/socket.module.ts
  backend/src/team/entity/team.entity.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/entity/user.entity.ts
  backend/src/workspace/dto/workspace.dto.ts
  backend/src/workspace/entity/workspace-member.entity.ts
  backend/src/workspace/entity/workspace.entity.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, BE

#150 [feat] create object 구현
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
  frontend/src/utils/socket.utils.ts
Labels: FE

#149 [feat] addSection 구현 closes #126
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/types/fabric-options.d.ts
  frontend/src/utils/fabric.utils.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#152 [feat] 객체 다중선택 구현 closes #151
  backend/src/socket/data-management.service.ts
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️, BE

#154 [fix] FE Resize 로직에 따른 workspace_object Entity의 컬럼명 변경 closes #153
  backend/src/migrations/1669751169830-change-object-columns-scale.ts
  backend/src/object-database/dto/create-object.dto.ts
  backend/src/object-database/dto/update-object.dto.ts
  backend/src/object-database/entity/workspace-object.entity.ts
  backend/src/socket/dto/object.dto.ts
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, 중요도⭐️, BE

#158 [hotfix] (un)select에서 typo로 인해 값을 못찾는 오류 수정 closes #154
  backend/src/socket/socket.gateway.ts
Labels: 실시간 공유 편집, BE

#156 [feat] 권한에 따른 인터페이스 처리 closes #128
  frontend/src/context/user.ts
  frontend/src/data/workspace-role.ts
  frontend/src/pages/main/workspace-menu/index.tsx
  frontend/src/pages/workspace/layout/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/index.tsx
  frontend/src/pages/workspace/whiteboard-canvas/useCanvas.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/fabric.utils.ts
Labels: 워크스페이스 초대 기능, 중요도⭐️⭐️⭐️, FE

#155 [feat] object update & text edit & remove & select & cursor 실시간 공유 구현
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/pages/workspace/whiteboard-canvas/types/socket.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-member.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/pages/workspace/whiteboard-canvas/useCanvasToSocket.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
  frontend/src/utils/socket.utils.ts
Labels: 실시간 공유 편집, 중요도⭐️⭐️⭐️, FE

#159 [feat] Text 편집 기능 구조 변경 closes #127
  frontend/patches/@types+fabric+4.5.12.patch
  frontend/src/pages/workspace/whiteboard-canvas/types/workspace-object.types.ts
  frontend/src/types/fabric-options.d.ts
  frontend/src/utils/object-from-server.ts
  frontend/src/utils/object.utils.ts
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#166 [hotfix] patch 파일 새로 받음 #127
  frontend/patches/@types+fabric+4.5.12.patch
Labels: 화이트보드, 중요도⭐️⭐️⭐️, FE

#165 [refactor] 모달 컴포넌트 리팩토링 closes #157
  frontend/src/components/error-modal/index.style.ts
  frontend/src/components/error-modal/index.tsx
  frontend/src/components/error-modal/index.types.ts
  frontend/src/components/github-login-button/index.tsx
  frontend/src/components/modal/index.style.tsx
  frontend/src/components/modal/index.tsx
  frontend/src/components/modal/index.types.ts
  frontend/src/components/user-profile/index.tsx
  frontend/src/pages/main/delete-modal/index.style.tsx
  frontend/src/pages/main/delete-modal/index.tsx
  frontend/src/pages/main/rename-modal/index.style.tsx
  frontend/src/pages/main/rename-modal/index.tsx
  frontend/src/pages/main/workspace-menu/index.tsx
  frontend/src/pages/workspace/index.style.tsx
  frontend/src/pages/workspace/index.tsx
  frontend/src/pages/workspace/layout/index.style.tsx
  frontend/src/pages/workspace/layout/index.tsx
  frontend/src/pages/workspace/share-modal/index.style.tsx
  frontend/src/pages/workspace/share-modal/index.tsx
  frontend/src/pages/workspace/share-modal/index.type.ts
  frontend/src/pages/workspace/whiteboard-canvas/useSocket.ts
Labels: 중요도⭐️, FE
